### PR TITLE
Added support for "Load more" feature

### PR DESCRIPTION
**Pull request by mpryvkin**
Added ability to dynamically load files in a folder containing large number of files. This significantly reduces loading time.

This helps to solve issues like #383 and #448.

### CODE REVIEW

**Comment by trippo** [comment]
thanks a lot @mpryvkin

**Comment by trippo** [comment]
sorry i removed this feature because it's not implement very well, please update creating a sort of api for load_more calls

**Comment by mpryvkin** [comment]
Did you have a chance to test it? What kind of API are you looking for?

IMHO, it just works based on the configuration options and no API methods are required.

**Comment by trippo** [comment]
Yes I tested but load every refresh all page IMHO it required a call to a new php page that return only a json with the files and folders and the query must render them

**Comment by mpryvkin** [comment]
I implemented it differently. The script calls dialog.php via Ajax which was adjusted to return only portion of the files/folders. There is no need for additional API.

Functionality is controlled by the following additional config options.

```
   // Enable "Load more" functionality
   'load_more' => false,
   // Number of files/folders displayed at once
   // Should be greater than "file_number_limit_js"
   'load_more_limit' => 120,
   // Enable auto-loading on scroll
   'load_more_auto' => auto,
```

**Comment by trippo** [comment]
Yes but return also a lot of html header,… and rendering it’s not correct

**Comment by mpryvkin** [comment]
Please point where rendering is not correct.

Regarding returning a lot of HTML header, that is still better than having the script hanging in a folder with large number of files.

In my project having this feature allowed to substantially reduce response time.

I don't have a problem if you don't want this feature, just wanted to contribute. Judging from number of issues about folder with large number of files, it's very needed.

**Comment by trippo** [comment]
You are right but I think it’s not a best method to do this

**Comment by mpryvkin** [comment]
If you change your mind, please let me know. I believe my implementation is still better because of minimal changes to the project.

**Comment by nicostem** [comment]
Hi, I have a folder with a large amount of files (+10k) that takes too long to load, I can't find anything else than your solution : can you explain to me how to add this to the current version? It would be really helpfull!

**Comment by mpryvkin** [comment]
@nicostem I will try to rebase [my fork](https://github.com/mpryvkin/ResponsiveFilemanager) against the current version later today.

**Comment by nicostem** [comment]
@mpryvkin thanks a lot!

**Comment by mpryvkin** [comment]
@nicostem, I forgot that this has already been merged into the main repository, please see #607.

**Comment by nicostem** [comment]
@mpryvkin It seems to have been removed as stated above ?

**Comment by mpryvkin** [comment]
@nicostem it has been merged into the master branch on May 22, 2020, see #607. Make sure you're using the most recent version.

**Comment by nicostem** [comment]
@mpryvkin thanks I was using the 9.14 but not the last files on github: your part is working fine, thanks a lot! I have other errors (in console and some weird styles) but not related, I guess it will be solved in next release.

**Pull request merged**
